# \uD398\uC774\uC9D5
page.size=10
page.block-size=5

# \uD30C\uC77C \uC800\uC7A5 \uACBD\uB85C
file.upload.path=C:/upload/profiles/

supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=curriculum
mybatis.configuration.map-underscore-to-camel-case=true

#\uB124\uC774\uBC84 \uBA54\uC77C \uBE44\uBC00\uBC88\uD638
mailSend.naver.username=alswo818
mailSend.naver.password=ETKFRJBSDT4W
