# \uD398\uC774\uC9D5
page.size=10
page.block-size=5

# \uB124\uC774\uBC84 \uBA54\uC77C \uBE44\uBC00\uBC88\uD638
naver.mail.passWord=RTHGRS3R3U77

# \uD30C\uC77C \uC800\uC7A5 \uACBD\uB85C
file.upload.path=C:/upload/profiles/
